### ISSUE TITLE
Using Cavy with multiple entry points

### ISSUE THREAD

**Issue by nabilfreeman** [pixielabs/cavy-cli#12]
Hey there, we have a project we are really interesting in integrating Cavy with.

Our app has four entry points:

`customerIndex.ios.js`
`customerIndex.android.js`
`proIndex.ios.js`
`proIndex.android.js`

So my thoughts are to have a `.test.js` for each of these... e.g.

`customerIndex.ios.test.js`

However I can't figure out how to specify which one to run with Cavy. It wants `index.test.js`.

It also does some renaming of the files so the Cavy'd file becomes the entry point for the build variant, which I understand but I could probably manually set this up in Xcode and Android Studio as test build variants.

Can I use Cavy entirely without the CLI and manually set up the test files?

Thank you! Really excited to give this a try

**Comment by AbigailMcP** [comment]
Hi there @nabilfreeman, thanks for your interest in using Cavy!

As you've probably noticed, cavy-cli just uses the `react-native-cli` under the hood, so if your set up doesn't allow you to boot the app using `react-native run-ios --some-other-arguments` then it's going to be tricky to use cavy-cli to run your tests.

However, you have some options:

**Cavy without cavy-cli**
You can run Cavy tests without cavy-cli. If you set up your four test files as you described, then booting your app from any one of these entry points will automatically run the tests and output the results to the console.

**Cavy with cavy-cli plus command line arguments**
The first use-case we had internally for cavy-cli was running our Cavy test suite in a Continuous Integration environment - specifically, we needed a way to signal the passing / failure of tests to CircleCI. For this case, Cavy on its own is not quite enough.

As you said, cavy-cli _does_ look for an `index.test.js` file when attempting to boot the app, however, if it doesn't find one, it continues and attempts to boot the app by running `react-native run-ios`. I'm not familiar with building RN apps with multiple entry points, but you can pass in any `react-native-cli` options that are valid for `react-native run-ios` to `cavy run-ios`- so this may be helpful for you.

**Custom reporter**
If you can't boot your app from the correct entry point using `react-native-cli`, then you'll have to do something custom to use Cavy. We're actually working on a native reporter for Cavy as an alternative to cavy-cli, which fires a Native Module callback when tests are finished. This means you'll be able to wire Cavy into your native test runner, such as XCTest. If you're using Xcode and Android Studio to boot and test your app, then this could be of use to you! I'll keep you posted on progress 👌

You'll also soon be able to write your own reporter handlers for Cavy and plug them in.

Hope this helps somewhat! I'll be really interested to hear how you get on, so please keep in touch. We're always thinking about ways to improve Cavy and appreciate any suggestions :)

**Comment by AbigailMcP** [comment]
I realise it won't solve your particular problem, but I'm going to add support for `index.android.test.js` and `index.ios.test.js` to the backlog as I'm sure a few RN projects out there have this setup! (#13)

**Comment by AbigailMcP** [comment]
Hi @nabilfreeman.

Just letting you know, we've now published our first custom reporter for Cavy, [Cavy Native Reporter](https://github.com/pixielabs/cavy-native-reporter), along with the ability to write your own reporter function to pass into Cavy.

Have a look at the README for Cavy Native Reporter](https://github.com/pixielabs/cavy-native-reporter) and check out the updated docs for custom reporters in [Cavy itself](https://github.com/pixielabs/cavy#writing-your-own-reporter) - might be useful!
