### ISSUE TITLE
Android and iOS entry points

### ISSUE THREAD

**Issue by AbigailMcP** [pixielabs/cavy-cli#13]
Support RN apps that have both `index.ios.js` and `index.android.js` entry points rather than a single `index.js`.

**Comment by TheAlmightyBob** [comment]
@AbigailMcP Was #14 expected to resolve this issue, or is it still in-progress? (i.e. should I create a new issue if support for `index.ios.js`/`index.android.js` files doesn't appear to be working with the `-file` option?)

**Comment by AbigailMcP** [comment]
Hi @TheAlmightyBob ! As per [this documentation](https://cavy.app/docs/guides/specifing-a-custom-app-entry-point), you should be able to pass in a file name to either `cavy run ios` or `cavy run-android` as the entry point for your app.

If you're having trouble with this, please do open an issue with the details of your set up and we'll take a look into this for you 👌

**Comment by TheAlmightyBob** [comment]
@AbigailMcP With #23 having been merged, I would think this issue could also be closed? So others don't (as I had) assume that this isn't expected to work yet.

**Comment by AbigailMcP** [comment]
Fixed in v1.3.3 https://github.com/pixielabs/cavy-cli/pull/23
