### ISSUE TITLE
TeamCity support

### ISSUE THREAD

**Issue by TheAlmightyBob** [pixielabs/cavy-cli#24]
Hi, I'd like to add TeamCity Test reporting support for Cavy, and am trying to figure out the most reasonable approach.

TeamCity actually supports specially-formatted console output messages that it can translate into its own rich test reporting, so the simplest approach would be to add an option for `cavy-cli` to switch to that format instead of the default human-readable output. Would it bother you for `cavy-cli` to have specialized knowledge of a specific CI system?

The option with minimal modification to Cavy would be to use the existing "custom reporting," however in this case we want pretty much everything the default reporter/server already does, just with tweaked output formatting, so that'd be a lot of duplication and managing another `express` server... (also I'm not sure how compatible `cavy-cli` is with this... since it won't exit until it receives a report... so the custom reporter would also have to report to `cavy-cli`...?)

I also see #18, and am wondering if there was a specific plan there? In addition to the special console logging, TeamCity also supports some report formats produced by other testing tools, listed here: https://www.jetbrains.com/help/teamcity/xml-report-processing.html . If you were already planning on using one of those formats for other CI systems, perhaps that would achieve multiple goals, but I'm not sure if that was the plan or how involved it would be to produce one of those reports.

It would be nice if `cavy-cli` could somehow support custom output formatter plugins, but that may not be feasible or useful outside this particular scenario.

Do you folks have any thoughts on this?

**Comment by AbigailMcP** [comment]
Hi @TheAlmightyBob - this sounds really interesting, and definitely in line with some of our internal ramblings surrounding #18.

Let me chat to the team about possible options and I'll get back to you in the next couple of days.

p.s. thanks for supporting Cavy! ❤️

**Comment by TheAlmightyBob** [comment]
Just in case you were curious, this is the special TeamCity console output format: https://www.jetbrains.com/help/teamcity/build-script-interaction-with-teamcity.html#BuildScriptInteractionwithTeamCity-ReportingTests

(One thing that'd generally help from the core Cavy side would be structured report data rather than (or in addition to) just a combined "message" property... but I expect that's a minor enhancement and not really a blocker here... but probably would also be wanted for #18)

**Comment by TheAlmightyBob** [comment]
(I'll also note that the console-logging route would be more compatible with #15 , as TeamCity does support that through this mechanism... but #15 seems like a nice-to-have)

**Comment by AbigailMcP** [comment]
Hi @TheAlmightyBob - just to let you know, we've just been pretty stacked this last week at Pixie Labs, but this is still on my radar!

**Comment by TheAlmightyBob** [comment]
@AbigailMcP Understood. In the meantime I've gone ahead and patched `cavy-cli` to optionally output TeamCity service messages. It's working, but we'd prefer to have a solution that others could use and doesn't require patching.

**Comment by AbigailMcP** [comment]
Hey @TheAlmightyBob ! We've had a think about this and propose that, for now, Cavy CLI should ship with some in-built formatters, in particular JSON and XML.

Later on, we might think about supporting format plugins, or custom formatters, simple to how we support customer reporters now.

How does that sound from your end? I'll use the JUnit spec for constructing the XML file.

**Comment by TheAlmightyBob** [comment]
@AbigailMcP That sounds like it should work. I'm not previously familiar with JUnit, but the XSD seems to support the required concepts.

I assume there's no point submitting a PR for the `--teamcity` flag that we already implemented?

**Comment by AbigailMcP** [comment]
Hi @TheAlmightyBob! Realise this was a while in the making... but we've just released new versions of cavy and cavy-cli that support outputting tests to a JUnit spec XML file! 🎉 

This should mean that TeamCity can support Cavy tests :)

Will close this issue for now, but if would love to hear any feedback you have on the new functionality. Thanks!

PR for this issue: https://github.com/pixielabs/cavy-cli/pull/28

**Comment by TheAlmightyBob** [comment]
@AbigailMcP Thanks for notifying me! Finally had a chance to look at this.

It looks pretty promising (and the addition of individual test durations is appreciated!). There's one quirk, which is that the results get duplicated in TeamCity:

![image](https://user-images.githubusercontent.com/7707864/90578980-8a8cd800-e179-11ea-9421-b6a6f1ac9736.png)

I'm curious what system(s) you tested this with and what the expected result was of having the same content in the "message" attribute and the element body?

All the info is present at least, but this isn't great for readability. I would love to use just the "message" attribute content but I don't think I can tell TeamCity to ignore the other data...

**Comment by AbigailMcP** [comment]
Thanks for reviewing!

We based this mainly on the XML we see produced by the [rspec-junit-formatter gem](https://github.com/sj26/rspec_junit_formatter), and [this JUnit Schema](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd).

The schema says:
- a `<Failure>` "Contains as a text node relevant data for the failure, e.g., a stack trace", and
- its `message` attribute should be "The message specified in the assert"

An example rspec-junit-formatter output would be:

```xml
<failure message="Expected to find text "EmployeeList.JimCavy" >

  Failure/Error: expect(page).to have_text "EmployeeList.JimCavy"
  Expected to find text "EmployeeList.JimCavy" 
  ./spec/features/employee_list_spec.rb:5:in `block (3 levels);

</failure>
```

In a similar fashion, an example cavy xml output would be:

```xml
<failure message="Could not find component with identifier EmployeeList.JimCavy" >

  Listing the employees: filters the list by search input  ❌
  Could not find component with identifier EmployeeList.JimCavy

</failure>
```

In both cases, the message is what failed in the assert and the body repeats the failure, but with extra context.

In general, I found it kinda tough to find a consensus for what should be included in each attribute to suit all needs! What would you guys expect to see in both the message and body of a failure?

**Comment by TheAlmightyBob** [comment]
Thanks for the explanation.

1. You're repeating the test name in the body, in addition to the error. I don't interpret either the schema or the rspec example as expecting that. That info is already captured by the parent node.
2. Your example includes blank lines around the body, but that's not what I see in the Cavy XML output, which is part of what makes it hard to read

```
<failure message="expect(received).toBe(expected) // Object.is equality&#xA;&#xA;Expected: &quot;expected&quot;&#xA;Received: &quot;Test text to write to the file&quot;" type="cavy test failure">The file system: can write and read a file  ❌
   expect(received).toBe(expected) // Object.is equality

Expected: "expected"
Received: "Test text to write to the file"</failure>
```
3. I realize one difference is that I'm directly using `expect` rather than Cavy's UI testing functions, so perhaps having a multi-line message with "expected"/"received" is different from what you're used to seeing.
4. Given that, what **I** would expect to see (and how I had previously set this up via patching) would be for the message to contain `expect(received).toBe(expected) // Object.is equality` and for the body to contain the `expected`/`received` lines.
5. Alternatively, since Cavy isn't actually producing stack traces... you could perhaps just leave the body empty and just use the message attribute? TeamCity at least appears to be handling that okay, although I don't know if other systems would expect the message to be single-line
