### ISSUE TITLE
Can't see test outputs

### ISSUE THREAD

**Issue by sabbir-a9s** [pixielabs/cavy-cli#34]
After running `cavy run-ios --skipbuild` in a react-native project using expo, I'm getting the following lines in console:

```
cavy: Found an index.test.js entry point. Temporarily replacing index.js to run tests.
cavy: Running `mv index.js index.notest.js && mv index.test.js index.js`...
cavy: Listening on port 8082 for test results...
```

The app is running in a simulator already but I don't see any test output in neither expo metro bundler nor the terminal console. Any suggestions on how to solve this issue and see my test results?

**Comment by TheAlmightyBob** [comment]
@sabbir0179 Assuming your `index.test.js` file is correctly configured to run the tests, did you reload the React Native app? When using the `--skipbuild` option, the tests won't automatically run until you manually trigger a reload.

**Comment by hoshinaoshi** [comment]
@TheAlmightyBob 
I have the same problem.
The detailed situation is like this.
https://github.com/pixielabs/cavy/issues/195#issuecomment-678972031

> the tests won't automatically run until you manually trigger a reload.

How do you do this?
Run from CLI? or is it the Command + D in the React Native App?

**Comment by TheAlmightyBob** [comment]
@hoshinaoshi cmd+D or cmd+R (or for Android emulator RR or cmd+M)

This isn't necessary if you don't use `--skipbuild`, since building/running will start the tests, but using `--skipbuild` just puts Cavy CLI in a passive mode listening for test results.

**Comment by hoshinaoshi** [comment]
@TheAlmightyBob 
Thank you for your answer. and I solved it.:bow:

@sabbir0179 

I made two mistakes.

1. Optional entry point when running the test
Expo specifies the entry point of the app because it is App.js.
Also, the test file will be App.test.js.

2. How to write App.test.js.
Initially I thought I would export App.js and use it in App.test.js.
But it wasn't.
App.test.js simply wrapped the render part of App.js in a Tester component.

Here is the working code.
https://github.com/hoshinaoshi/cavyTest

**Comment by AbigailMcP** [comment]
Glad you got this sorted @hoshinaoshi :) and thanks for helping @TheAlmightyBob !

@hoshinaoshi - are there any parts of the documentation you think could be improved? I'm thinking a page specifically for Expo set up... we have a [Custom Entry Point Guide](https://cavy.app/docs/guides/specifing-a-custom-app-entry-point) but maybe this is too hidden away.

**Comment by AbigailMcP** [comment]
@sabbir0179 - I'm closing this issue for now but please let me know whether you're still having trouble and I'll reopen.
