### ISSUE TITLE
cavy command for expo project

### ISSUE THREAD

**Issue by matteocollina** [pixielabs/cavy-cli#4]
Is it possibile to add cavy cmd for expo project without ios and android folder? 
thanks

**Comment by AbigailMcP** [comment]
Hi @matteocollina - thanks for bringing this to our attention. It's not something we're actively working on at the moment, but we'll investigate how we might approach adding expo functionality in the future.

**Comment by AbigailMcP** [comment]
Closing this old issue! We did not add this feature to the roadmap, but cavy tests can be run via cavy-cli with the `--skipbuild` option, which assumes your app is already running, and listens for test results. This can be used in expo projects!
