### ISSUE TITLE
Cavy not testing all test case

### ISSUE THREAD

**Issue by deceive3w** [pixielabs/cavy-cli#5]
in my test case there having async timeout, but cavy cli get stoped while my test case is not resolve

**Comment by AbigailMcP** [comment]
Hey there - can you give us a little more detail on what is happening? Also, have you tried running your tests without `cavy-cli`? What happens in this case?

**Comment by deceive3w** [comment]
yes its work without cavy-cli, but running in cavy-cli test is stopped in first test

**Comment by deceive3w** [comment]
```
spec.describe('Test', async function() {
      spec.it('should markets item', async function() {
        await spec.pause(10000)
        await spec.exists('Markets.Item');
      });
       //this section is not called, but without cavy-cli its work
        spec.it('should can navigate to markets detail', async function(){
          const marketsItem = await spec.findComponent('Markets.Item')
            marketsItem.props.openDetail(marketsItem.props.item)
            await spec.exists('Markets.Detail');
            const marketDetail = await spec.findComponent('Markets.Detail');
            await marketDetail.props.navigator.pop()
            await spec.pause(1000)
            spec.it('should can navigate to login screen', async function(){
              const marketIndex = await spec.findComponent('Markets.Index')
              await marketIndex.props.navigator.switchToTab({tabIndex: 2})
            })
     })
})

**Comment by AbigailMcP** [comment]
Hmm @deceive3w - I can't immediately see why that wouldn't work... could you give me some details about your environment? We've had a couple of issues from people running cavy-cli on windows - is that true for you?

**Comment by jalada** [comment]
I'm going to close this as we've not heard anything back, but please comment if you have more information for us :)
